CREATE DATABASE IF NOT EXISTS lab3;
USE lab3;
CREATE TABLE IF NOT EXISTS team (id int, name String);
CREATE TABLE IF NOT EXISTS team_member (id int, name String, team_id int);
CREATE TABLE IF NOT EXISTS car (id int, name String, team_id int, year int);
INSERT INTO team VALUES (1, 'MADI');
INSERT INTO team VALUES (2, 'MIREA');
INSERT INTO team_member VALUES (1, 'Gumbin Alex', 1);
INSERT INTO team_member VALUES (2, 'Gumbin Ivan', 1);
INSERT INTO team_member VALUES (3, 'Gumbin Max', 2);
INSERT INTO team_member VALUES (4, 'Gumbin Andrew', 2);
INSERT INTO car VALUES (1, 'FSM-6', 1, 2016);
INSERT INTO car VALUES (2, 'FSM-5', 1, 2014);
INSERT INTO car VALUES (3, 'MIREA-15', 2, 2015);
INSERT INTO car VALUES (4, 'MIREA-10', 2, 2010);
SELECT * FROM team;
SELECT * FROM team_member WHERE team_id = 2;
SELECT * FROM team JOIN team_member on team.id = team_member.team_id;
SELECT * FROM team JOIN car on team.id = car.team_id;
SELECT * FROM team JOIN car on team.id = car.team_id ORDER BY car.year ASC;
